# =============================================================================
# refence_data/compute_reference_params.R
#
# Generates the internal standardization parameters used by
# compute_urban_index() to anchor urbanicity scores to the PEcAHN global
# reference distribution.
#
# WHEN TO RUN THIS SCRIPT
# -----------------------
# Run this script whenever the reference dataset is updated (e.g., new
# communities added, GEE extraction re-run with updated covariates). After
# running, rebuild and reinstall the package so the new parameters take effect:
#
#   source("refence_data/compute_reference_params.R")
#   devtools::document()
#   devtools::install()
#
# WHAT THIS SCRIPT DOES
# ---------------------
# 1. Loads the PEcAHN global reference dataset from reference_data/.
# 2. Resolves the most recent available year for multi-year variables
#    (nighttime_light, pop_density).
# 3. Computes per-feature standardization parameters for both methods:
#      - z-score: mean and SD
#      - min-max: minimum and range (max - min)
#    Parameters for multi-year variables are stored under the feature stub
#    (e.g., "nighttime_light") rather than the year-specific column name
#    (e.g., "nighttime_light_2025"). This ensures that input data from any
#    collection year is correctly matched to the reference parameters at
#    runtime, regardless of which year the reference was built from.
# 4. Saves the resulting object (.urbanicity_ref_params) to R/sysdata.rda,
#    R's standard location for internal package data. This file is loaded
#    automatically when the package is attached; users never interact with
#    it directly.
# 5. Verifies the saved file loads correctly and contains the expected keys.
#
# INPUT
# -----
#   reference_data/urbanicity_reference_dataset.rds
#     A data frame of ~1,400 globally distributed communities with GEE-derived
#     urbanicity covariates. Generated by compute_urbanicity_iterative() and
#     stored in reference_data/ (tracked in the repository). This file is the
#     single source of truth for the reference distribution; do not modify it
#     manually.
#
# OUTPUT
# ------
#   R/sysdata.rda
#     Internal package data file containing .urbanicity_ref_params, a named
#     list with elements:
#       $zscore  -- per-feature list of center (mean) and scale (SD)
#       $minmax  -- per-feature list of center (min) and scale (range)
#       $meta    -- provenance: n_communities, resolved column names,
#                  feature-to-stub key map, generation timestamp, R version
#
# NOTE ON save() vs. usethis::use_data()
# ---------------------------------------
# This script uses base::save() directly rather than usethis::use_data().
# usethis::use_data(..., internal = TRUE) constructs the object list from
# argument names, and some versions silently exclude leading-dot names like
# .urbanicity_ref_params because ls() does not return dot-names by default.
# Using save() directly is unambiguous and avoids this failure mode.
# =============================================================================


# ------------------------------------------------------------------------------
# 1. Load reference dataset
# ------------------------------------------------------------------------------
ref_path <- "/Users/levkolinski/Desktop/pecahn-urbanicity/reference_data/urbanicity_reference_dataset.rds"

if (!file.exists(ref_path)) {
  stop(
    "Reference dataset not found at: ", ref_path, "\n",
    "Run this script from the package root directory:\n",
    "  setwd('/path/to/pecahnurbanicity')\n",
    "  source('data-raw/compute_reference_params.R')"
  )
}

ref <- readRDS(ref_path)
message("Loaded reference dataset: ", nrow(ref), " communities, ",
        ncol(ref), " columns")


# ------------------------------------------------------------------------------
# 2. Feature configuration
#
# features:        The six core urbanicity covariates included in the composite.
# multiyear_stubs: Features for which GEE extraction produces one column per
#                  year (e.g., nighttime_light_2025, nighttime_light_2025).
#                  The most recent available year is used for the reference
#                  parameters.
# ------------------------------------------------------------------------------
features <- c(
  "pct_paved_roads",
  "travel_time_hospital_min",
  "travel_time_school_min",
  "travel_time_urban_center_min",
  "nighttime_light",
  "pop_density"
)

multiyear_stubs <- c("nighttime_light", "pop_density")


# ------------------------------------------------------------------------------
# 3. Resolve actual column names from feature stubs
#
# For multi-year stubs, all year-suffixed columns (e.g., nighttime_light_2025,
# nighttime_light_2025) are detected and the most recent year is selected.
#
# Two parallel vectors are built:
#   resolved_cols  -- the actual column name used (e.g., "nighttime_light_2025")
#   ref_key_map    -- named vector mapping actual col -> stub
#                     (e.g., "nighttime_light_2025" -> "nighttime_light")
#
# Storing params under the stub rather than the year column is the critical
# design decision that makes the reference year-agnostic at runtime: input
# data with nighttime_light_2024 will look up "nighttime_light" in ref_params
# and correctly find the parameters derived from nighttime_light_2025.
# ------------------------------------------------------------------------------
resolved_cols <- character(0)
ref_key_map   <- character(0)

for (feat in features) {
  if (feat %in% multiyear_stubs) {
    
    pattern   <- paste0("^", feat, "_[0-9]{4}$")
    year_cols <- grep(pattern, colnames(ref), value = TRUE)
    
    if (length(year_cols) == 0) {
      # Fall back to bare column if no year-suffixed version exists
      if (feat %in% colnames(ref)) {
        resolved_cols[feat] <- feat
        ref_key_map[feat]   <- feat
        message(sprintf("  '%s': no year-suffixed columns found; using bare column", feat))
      } else {
        stop("Feature '", feat, "' not found in reference dataset. ",
             "Check that compute_urbanicity_iterative() has been run and the ",
             "output saved to reference_data/urbanicity_reference_dataset.rds.")
      }
    } else {
      years      <- as.integer(regmatches(year_cols, regexpr("[0-9]{4}$", year_cols)))
      chosen_col <- year_cols[which.max(years)]
      resolved_cols[feat]     <- chosen_col
      ref_key_map[chosen_col] <- feat   # year col -> stub key
      message(sprintf("  '%s': using '%s' (year %d) -- stored under stub key '%s'",
                      feat, chosen_col, max(years), feat))
    }
    
  } else {
    if (!feat %in% colnames(ref)) {
      stop("Feature '", feat, "' not found in reference dataset.")
    }
    resolved_cols[feat] <- feat
    ref_key_map[feat]   <- feat
    message(sprintf("  '%s': using column '%s'", feat, feat))
  }
}

message("\nResolved columns:   ", paste(resolved_cols, collapse = ", "))
message("Reference key map:  ",
        paste(paste0(resolved_cols, " -> ", ref_key_map[resolved_cols]),
              collapse = ", "))


# ------------------------------------------------------------------------------
# 4. Compute standardization parameters, keyed by stub name
#
# For each resolved column, compute the parameters needed for the requested
# standardization method, stored under the stub key (not the year col name).
#
#   z-score:  center = mean, scale = SD
#   min-max:  center = min,  scale = range (max - min)
# ------------------------------------------------------------------------------
.compute_params <- function(data, resolved_cols, ref_key_map, method) {
  params <- list()
  for (col in resolved_cols) {
    key <- ref_key_map[[col]]
    x   <- as.numeric(data[[col]])
    n   <- sum(!is.na(x))
    
    if (n < 10) {
      warning("Column '", col, "' has only ", n,
              " non-missing values in the reference dataset -- skipping. ",
              "Check for extraction failures in urbanicity_reference_dataset.rds.")
      next
    }
    
    if (method == "zscore") {
      center <- mean(x, na.rm = TRUE)
      scale  <- sd(x,   na.rm = TRUE)
      if (scale == 0) {
        warning("Column '", col, "' has zero variance -- skipping.")
        next
      }
    } else {
      center <- min(x, na.rm = TRUE)
      scale  <- max(x, na.rm = TRUE) - center
      if (scale == 0) {
        warning("Column '", col, "' has zero range -- skipping.")
        next
      }
    }
    
    params[[key]] <- list(center = center, scale = scale)
    message(sprintf("  [%s] %-35s  center = %10.4f  scale = %10.4f",
                    method, key, center, scale))
  }
  params
}

message("\n--- Z-score parameters (center = mean, scale = SD) ---")
zscore_params <- .compute_params(ref, resolved_cols, ref_key_map, "zscore")

message("\n--- Min-max parameters (center = min, scale = range) ---")
minmax_params <- .compute_params(ref, resolved_cols, ref_key_map, "minmax")


# ------------------------------------------------------------------------------
# 5. Assemble the internal object
#
# .urbanicity_ref_params is the object loaded at runtime by compute_urban_index().
# The leading dot makes it invisible to users (ls() skips dot-names by default)
# while remaining accessible within package functions.
#
# meta is included for provenance: calling urbanicity_ref_params() will print
# which year columns were used and when the parameters were generated, making
# it straightforward to verify that the installed package reflects the expected
# version of the reference dataset.
# ------------------------------------------------------------------------------
.urbanicity_ref_params <- list(
  zscore = zscore_params,
  minmax = minmax_params,
  meta   = list(
    n_communities   = nrow(ref),
    features        = features,
    multiyear_stubs = multiyear_stubs,
    resolved_cols   = resolved_cols,   # actual columns used (year-specific)
    ref_key_map     = ref_key_map,     # col -> stub, for provenance
    generated_at    = Sys.time(),
    r_version       = R.version.string
  )
)

# Sanity check before writing to disk
stopifnot(
  is.list(.urbanicity_ref_params$zscore),
  is.list(.urbanicity_ref_params$minmax),
  length(.urbanicity_ref_params$zscore) == length(features),
  length(.urbanicity_ref_params$minmax) == length(features),
  identical(sort(names(.urbanicity_ref_params$zscore)),
            sort(names(.urbanicity_ref_params$minmax)))
)

message(sprintf(
  "\nObject assembled: zscore (%d keys), minmax (%d keys), n_ref = %d",
  length(.urbanicity_ref_params$zscore),
  length(.urbanicity_ref_params$minmax),
  .urbanicity_ref_params$meta$n_communities
))


# ------------------------------------------------------------------------------
# 6. Save to R/sysdata.rda
#
# R/sysdata.rda is the standard location for internal package data (objects
# accessible to package functions but not exported to users). It is loaded
# automatically when the package namespace is loaded.
#
# If sysdata.rda already exists (e.g., from a previous run or other internal
# objects), existing objects are preserved and only .urbanicity_ref_params is
# updated.
# ------------------------------------------------------------------------------
sysdata_path <- "R/sysdata.rda"

if (!dir.exists("R")) {
  dir.create("R")
  message("Created R/ directory.")
}

existing_objects <- character(0)
if (file.exists(sysdata_path)) {
  existing_env <- new.env(parent = emptyenv())
  load(sysdata_path, envir = existing_env)
  existing_objects <- ls(existing_env, all.names = TRUE)
  existing_objects <- setdiff(existing_objects, ".urbanicity_ref_params")
  if (length(existing_objects) > 0) {
    message("Preserving existing sysdata objects: ",
            paste(existing_objects, collapse = ", "))
    for (obj in existing_objects) {
      assign(obj, get(obj, envir = existing_env))
    }
  }
}

save(
  .urbanicity_ref_params,
  list     = existing_objects,
  file     = sysdata_path,
  compress = "xz"
)

message("Written to: ", sysdata_path)


# ------------------------------------------------------------------------------
# 7. Verify the saved file loads correctly
#
# Reload the .rda into a fresh environment and confirm the object is present
# and well-formed before declaring success. This catches the leading-dot
# save() failure mode and any other serialization issues immediately.
# ------------------------------------------------------------------------------
verify_env <- new.env(parent = emptyenv())
load(sysdata_path, envir = verify_env)
saved_names <- ls(verify_env, all.names = TRUE)

message("\nVerification -- objects in ", sysdata_path, ":")
message("  ", paste(saved_names, collapse = ", "))

if (!".urbanicity_ref_params" %in% saved_names) {
  stop(
    "Verification FAILED: .urbanicity_ref_params not found in saved file.\n",
    "Check that base::save() is being called with the object directly, not ",
    "via a character string in the `list` argument."
  )
}

loaded <- get(".urbanicity_ref_params", envir = verify_env)
message(sprintf("  zscore keys: %s", paste(names(loaded$zscore), collapse = ", ")))
message(sprintf("  minmax keys: %s", paste(names(loaded$minmax), collapse = ", ")))
message(sprintf("  n_communities: %d", loaded$meta$n_communities))
message(sprintf("  generated_at:  %s",
                format(loaded$meta$generated_at, "%Y-%m-%d %H:%M %Z")))

message(
  "\nVerification passed.\n",
  "Run devtools::document() then devtools::install() to make the updated\n",
  "parameters available in the installed package."
)
